// <auto-generated />
namespace BTv7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SaleTypeOrderModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleTypeOrderModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231325448_SaleTypeOrderModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
