// <auto-generated />
namespace BTv7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LoginDataInput : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoginDataInput));
        
        string IMigrationMetadata.Id
        {
            get { return "202012231440293_LoginDataInput"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
